# Q.1 Arrays

In [2]:
import numpy as np
def arrays(arr):
    # complete this function
    # use numpy.array
    arr=np.array(arr, float)[::-1]
    return arr
    

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 5 -12 -5
[ -5. -12.   5.   4.   3.   2.   1.]


# Q.2 Shape and Reshape

In [9]:
# creating user defined list of array
l=np.array(input().split(), int)

# printing the array of list
print(l)

# printing the shape of the list "l"
print(l.shape)

# Shape function used to change the dimensions of an array
l.shape=(3,3)
print(l)

1 2 3 4 5 6 7 8 9
[1 2 3 4 5 6 7 8 9]
(9,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# Using the reshape function to change the dimension of an array
print(np.reshape(l,(3,3)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Q.3 Transpose and Flatten

In [17]:
# define the number of rows and columns N and M
N=int(input("enter the number of rows in array list : "))
M=int(input("enter the no. of columns in array list : "))

# Ceating and print user define array list and dimension of an array
l=np.array(input().split(), int)
List=np.reshape(l, (N,M))
print(List)

# printing the transposition of an array using the tool numpy.transpose.
print(np.transpose(List))

# The tool flatten creates a copy of the input array flattened to one dimension.
print(List.flatten())

enter the number of rows in array list : 2
enter the no. of columns in array list : 3
1 2 3 4 5 6
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]


In [19]:
N,M=map(int ,input().split())

List = np.array( [(input().split()) for i in range(N)] , int)
print(np.transpose(List))
print(List.flatten())

2 2 
1 2 
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


# Q.4 Concatenate

In [29]:
import numpy as np
N,M,P=map(int, input().split())

# Creating and print user define array list and dimension of an array
arr_1=np.array([input().split() for i in range(N)],int)
arr_2=np.array([input().split() for j in range(M)], int)
print('*'*30)
print(arr_1)
print('*'*30)
print(arr_2)
print('*'*30)
# Two or more arrays can be concatenated together using the concatenate function with a tuple of the arrays to be joined
print(np.concatenate((arr_1,arr_2), axis=0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
******************************
[[1 2]
 [1 2]
 [1 2]
 [1 2]]
******************************
[[3 4]
 [3 4]
 [3 4]]
******************************
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


# Q.5 Zeros and Ones

In [32]:

N=list(map(int, input().split()))

print(np.zeros(N,int))
print(np.ones(N, int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


# Q.6 Eye and Identity

In [49]:
import numpy as np

# In order to get alignment correct, we have to insert the line "np.set_printoptions(legacy='1.13')"
np.set_printoptions(legacy='1.13')
N,M=list(map(int, input().split()))

# The identity tool returns an identity array
print(np.identity(N))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [50]:
# The eye tool returns a 2-D array with 1's as the diagonal and 0's elsewhere. 
# The diagonal can be main, upper or lower depending on the optional parameter k.
# A positive k is for the upper diagonal, a negative k is for the lower, and a k=0  (default) is for the main diagonal.
print(np.eye(N,M, k=0))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


# Q.7 Array Mathematics

In [57]:
N,M=map(int ,input().split())

A = np.array( [(input().split()) for i in range(N)] , int)
B = np.array( [(input().split()) for i in range(N)] , int)

# adding the element wise in two arrays
print("adding two arrays elements wise :",A+B)

# substracting the elements of B from A
print("substacting two arrays element wise :",A-B)

# multipling the elements of two arrays
print("multipling two arrays element wise",A*B)

# divideing the elements of the two arrays
print("Integer Division of two arrays element wise :",A//B)

# modulo of the elements wise of the two arrays
print("modulos of A and B : ",A%B)

# powes of the element-wise in two arrays
print("power of the elements of two arrays : ",A**B)

1 4
1 2 3 4
5 6 7 8
adding two arrays elements wise : [[ 6  8 10 12]]
substacting two arrays element wise : [[-4 -4 -4 -4]]
multipling two arrays element wise [[ 5 12 21 32]]
Integer Division of two arrays element wise : [[0 0 0 0]]
modulos of A and B :  [[1 2 3 4]]
power of the elements of two arrays :  [[    1    64  2187 65536]]


In [56]:
print(np.add(A,B))
print(np.subtract(A,B))
print(np.multiply(A,B))
print(np.divide(A,B))
print(np.mod(A,B))
print(np.power(A,B))

[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[ 0.2         0.33333333  0.42857143  0.5       ]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


# Q.8 Floor, Ceil and Rint 

In [65]:
# creating an user define array
A=np.array(input().split(), float)
np.set_printoptions(legacy='1.13')

# printing the list of an array
print(A)

# The tool floor returns the floor of the input element-wise.
print(np.floor(A))

# The tool ceil returns the ceiling of the input element-wise.
print(np.ceil(A))

# The rint tool rounds to the nearest integer of input element-wise.
print(np.rint(A))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.1  2.2  3.3  4.4  5.5  6.6  7.7  8.8  9.9]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


# Q.9 Sum and Prod

### Task

#### You are given a 2-D array with dimensions $N \times M$.
#### Your task is to perform the sum tool over axis 0 and then find the product of that result.

In [78]:
# ceating the user define array
N,M=map(int ,input().split())
List = np.array( [(input().split()) for i in range(N)] , int)
print("*"*40)
# printing the list of array
print(List)
print("*"*40)
# The sum tool returns the sum of array elements over a given axis.
print(np.sum(List))

print("*"*40)
print(np.sum(List, axis=0))
print("*"*40)
print(np.sum(List, axis=1))
print("*"*40)
# The prod tool returns the product of array elements over a given axis.
print(np.prod(List))
print("*"*40)
print(np.prod(List, axis=0))
print("*"*40)
print(np.prod(List, axis=1))
print("*"*40)
# To perform the sum tool over axis 0 and then find the product of that result.
print(np.prod(np.sum(List)))
print(np.prod(np.sum(List, axis=0)))
print(np.prod(np.sum(List, axis=1)))
print("*"*40)
# To perform the prod tool over axis 0 and then find the sum of that result.
print(np.sum(np.prod(List)))
print(np.sum(np.prod(List, axis=0)))
print(np.sum(np.prod(List, axis=1)))

3 3
1 1 1
1 1 1
1 1 1
****************************************
[[1 1 1]
 [1 1 1]
 [1 1 1]]
****************************************
9
****************************************
[3 3 3]
****************************************
[3 3 3]
****************************************
1
****************************************
[1 1 1]
****************************************
[1 1 1]
****************************************
9
27
27
****************************************
1
3
3


# Q.10 Min and Max

In [80]:
# ceating the user define array
N,M=map(int ,input().split())
List = np.array( [(input().split()) for i in range(N)] , int)
print(List)
print("*"*40)

# The tool min returns the minimum value along a given axis.
print(np.min(List))
print(np.min(List, axis=0))
print(np.min(List, axis=1))
print("*"*40)

# The tool max returns the maximum value along a given axis.
print(np.max(List))
print(np.max(List, axis=0))
print(np.max(List, axis=1))
print("*"*40)

# To perform the min function over axis 1 and then find the max of that.
print(np.max(np.min(List)))
print(np.max(np.min(List, axis=0)))
print(np.max(np.min(List, axis=1)))

4 2
2 5
3 7
1 3
4 0
[[2 5]
 [3 7]
 [1 3]
 [4 0]]
****************************************
0
[1 0]
[2 3 1 0]
****************************************
7
[4 7]
[5 7 3 4]
****************************************
0
1
3


# Q.11 Mean, Var, and Std

You are given a 2-D array of size $ N \times M $.

### Task is to find:

##### The mean along axis 
##### The var along axis 
##### The std along axis 

In [82]:
# ceating the user define array
N,M=map(int ,input().split())
List = np.array( [input().split() for i in range(N)] , int)
print(List)
print("*"*40)

# The mean along axis
print(np.mean(List))
print(np.mean(List, axis=0))
print(np.mean(List, axis=1))
print("*"*40)

# The var along axis
print(np.var(List))
print(np.var(List, axis=0))
print(np.var(List, axis=1))
print("*"*40)

# The std along axis
print(np.std(List))
print(np.std(List, axis=0))
print(np.std(List, axis=1))

2 2
1 2
3 4
[[1 2]
 [3 4]]
****************************************
2.5
[ 2.  3.]
[ 1.5  3.5]
****************************************
1.25
[ 1.  1.]
[ 0.25  0.25]
****************************************
1.11803398875
[ 1.  1.]
[ 0.5  0.5]


# Q.12 Dot and Cross

In [89]:
# You are given two arrays A and B. Both have dimensions of NXN.
N=int(input())
A = np.array( [(input().split()) for i in range(N)] , int)
B = np.array( [(input().split()) for i in range(N)] , int)
print("--%--"*10)

# printing the matrices' 
print("A : ",A)
print("B : ",B)
print("--%--"*10)

# The dot tool returns the dot product of two arrays.
print(np.dot(A,B))
print("--%--"*10)

# The cross tool returns the cross product of two arrays.
print(np.cross(A,B))

2
1 2
3 4
1 2
3 4
--%----%----%----%----%----%----%----%----%----%--
A :  [[1 2]
 [3 4]]
B :  [[1 2]
 [3 4]]
--%----%----%----%----%----%----%----%----%----%--
[[ 7 10]
 [15 22]]
--%----%----%----%----%----%----%----%----%----%--
[0 0]


# Q.13 Inner and Outer

In [94]:
A = np.array( (input().split())  , int)
B = np.array( (input().split())  , int)
print("*"*30)
print(A)
print(B)
print("*"*30)

#The inner tool returns the inner product of two arrays.
print(np.inner(A,B))
print("*"*30)

# The outer tool returns the outer product of two arrays.
print(np.outer(A,B))

0 1
2 3
******************************
[0 1]
[2 3]
******************************
3
******************************
[[0 0]
 [2 3]]


# Q.14 Polynomials

In [101]:
# creating the coefficients of a polynomial .
P=np.array( (input().split())  , float)

# printing the polynomial 
print(P)

# giving the contains the value of x
x=float(input())

# Print the desired value.
print(np.polyval(P,x))

1.1 2 3
[ 1.1  2.   3. ]
0
3.0


# Q.15 Linear Algebra

In [105]:
# ceating the user define array
N=int(input())
A = np.array( [(input().split()) for i in range(N)] , float)
print("*"*30)

# printing the array
print(A)
print("*"*30)

# Print the determinant of A.
print(np.linalg.det(A))


2
1.1 1.1
1.1 1.2
******************************
[[ 1.1  1.1]
 [ 1.1  1.2]]
******************************
0.11
